 
### Manajemen Komentar  
  
# Tampilkan Komentar Konten  
GET http://localhost:<port>/contents/1/comments  
  
# Buat Komentar Konten  
POST http://localhost:<port>/contents/1/comments  
Authorization: Bearer <token>  
Content-Type: application/json  
  
{  
    "comment": "Ini adalah komentar untuk konten."  
}  
  
# Hapus Komentar  
DELETE http://localhost:<port>/contents/comments/1  
Authorization: Bearer <token>  
