
### Pelacakan Penyelesaian Konten  
  
# Tambah Pelacakan Penyelesaian  
POST http://localhost:<port>/completion  
Authorization: Bearer <token>  
Content-Type: application/json  
  
{  
    "courseId": 1,  
    "contentId": 1  
}  
  
# Tampilkan Pelacakan Penyelesaian  
GET http://localhost:<port>/completion/1  
  
# Hapus Pelacakan Penyelesaian  
DELETE http://localhost:<port>/completion/1  
  