
### Manajemen Kursus  
  
# Daftar Kursus  
GET http://localhost:3000/api/courses
  
### Detail Kursus  
GET http://localhost:3000/api/courses/1  
  
### Kursus Saya  
GET http://localhost:3000/api/myCourses 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUyLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTczNjU5NjE1NSwiZXhwIjoxNzM2NTk5NzU1fQ.xMZLyrL9-Bdn3tvpGkwidGHMLP2fTmba4T5h6yT8RDE 
  
### Buat Kursus  
POST http://localhost:3000/api/courses 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUyLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTczNjU5NjE1NSwiZXhwIjoxNzM2NTk5NzU1fQ.xMZLyrL9-Bdn3tvpGkwidGHMLP2fTmba4T5h6yT8RDE  
Content-Type: application/json  
  
{  
    "name": "Kursus Baru",  
    "description": "Deskripsi kursus baru",  
    "price": 100000,  
    "url": "coursera.com",
    "site": "http://example.com",  
    "categoryId": null  
}  
  
### Perbarui Kursus  
PUT http://localhost:3000/api/courses/1  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUyLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTczNjU5NjE1NSwiZXhwIjoxNzM2NTk5NzU1fQ.xMZLyrL9-Bdn3tvpGkwidGHMLP2fTmba4T5h6yT8RDE  
Content-Type: application/json  
  
{  
    "name": "Kursus Diperbarui",  
    "description": "Deskripsi kursus yang diperbarui",  
    "price": 150000,  
    "site": "http://example.com",  
    "categoryId": 1  
}  
  
### Daftar di Kursus  
POST http://localhost:3000/api/courses/1/enroll  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUyLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTczNjU5NjE1NSwiZXhwIjoxNzM2NTk5NzU1fQ.xMZLyrL9-Bdn3tvpGkwidGHMLP2fTmba4T5h6yT8RDE    
  