
### Umpan Balik Kursus  
  
# Tambah Umpan Balik  
POST http://localhost:<port>/course/1/feedback  
Authorization: Bearer <token>  
Content-Type: application/json  
  
{  
    "feedback": "Kursus ini sangat membantu!"  
}  
  
# Tampilkan Umpan Balik  
GET http://localhost:<port>/course/1/feedback  
  
# Edit Umpan Balik  
PUT http://localhost:<port>/course/1/feedback/1  
Authorization: Bearer <token>  
Content-Type: application/json  
  
{  
    "feedback": "Umpan balik yang diperbarui."  
}  
  
# Hapus Umpan Balik  
DELETE http://localhost:<port>/course/1/feedback/1  
Authorization: Bearer <token>  
  
