
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://michelle:michelle123@db:5432/uas_db_be
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db-uas-pss
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: michelle
      POSTGRES_PASSWORD: michelle123
      POSTGRES_DB: uas_db_be
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
